### ISSUE TITLE
I started getting this Faraday error recently

### ISSUE THREAD

**Issue by xcfw** [HeRoMo/pronto-action#508]
I'm using this workflow:

```yaml
name: Code quality
on:
  pull_request:
    types: [ 'synchronize', 'labeled', 'review_requested' ]

jobs:
  pronto:
    permissions:
      pull-requests: write
      statuses: write     
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: HeRoMo/pronto-action@v1.63.0
```

And getting this error:
```sh
COMMAND: bundle exec pronto run /github/workspace/. -c origin/main -r rubocop -f github_status github_pr
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
bundler: failed to load command: pronto (/usr/local/bundle/bin/pronto)
/usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load': cannot load such file -- standard (LoadError)
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:39:in `rescue in load'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:32:in `load'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:21:in `load'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:52:in `load_file'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:111:in `configuration_from_file'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_store.rb:68:in `for_dir'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_store.rb:58:in `for'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:41:in `rubocop_config'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:50:in `valid?'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:14:in `messages'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `block in run'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `each'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `flat_map'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:20:in `block in run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:13:in `each'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:13:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto.rb:66:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:70:in `block in run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `chdir'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/pronto-0.11.2/bin/pronto:6:in `<top (required)>'
	from /usr/local/bundle/bin/pronto:25:in `load'
	from /usr/local/bundle/bin/pronto:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- standard (LoadError)
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:42:in `rescue in load'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:32:in `load'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:21:in `load'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:52:in `load_file'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:111:in `configuration_from_file'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_store.rb:68:in `for_dir'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_store.rb:58:in `for'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:41:in `rubocop_config'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:50:in `valid?'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:14:in `messages'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `block in run'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `each'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `flat_map'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:20:in `block in run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:13:in `each'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:13:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto.rb:66:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:70:in `block in run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `chdir'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/pronto-0.11.2/bin/pronto:6:in `<top (required)>'
	from /usr/local/bundle/bin/pronto:25:in `load'
	from /usr/local/bundle/bin/pronto:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- standard (LoadError)
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:35:in `load'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/feature_loader.rb:21:in `load'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:52:in `load_file'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_loader.rb:111:in `configuration_from_file'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_store.rb:68:in `for_dir'
	from /usr/local/bundle/gems/rubocop-1.64.1/lib/rubocop/config_store.rb:58:in `for'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:41:in `rubocop_config'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:50:in `valid?'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:14:in `messages'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `block in run'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `each'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `flat_map'
	from /usr/local/bundle/gems/pronto-rubocop-0.11.5/lib/pronto/rubocop.rb:13:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:20:in `block in run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:13:in `each'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/runners.rb:13:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto.rb:66:in `run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:70:in `block in run'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `chdir'
	from /usr/local/bundle/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/pronto-0.11.2/bin/pronto:6:in `<top (required)>'
	from /usr/local/bundle/bin/pronto:25:in `load'
	from /usr/local/bundle/bin/pronto:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/bundle/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'
```

**Comment by HeRoMo** [comment]
Thank you for your report.

I tested HeRoMo/pronto-action@v1.63.0 in my ruby repository,but pronto-action runs successfuly.

**Comment by xcfw** [comment]
The issue is still there even after update to `1.65.0`, we have a ruby and js monorepo and have both package.json and Gemfile in the root folder I wonder if this somehow messes up workflow runs, so they fail each and every time:

<img width="1381" alt="image" src="https://github.com/user-attachments/assets/88d14306-a254-497d-97ae-fd292c905df2">

**Comment by xcfw** [comment]
Maybe the issue is with private repos or that it's the organization owned repo?

**Comment by HeRoMo** [comment]
I think the reason of this error is missing *starndard* gem.
what rubocop plugin do you use in your project?

**Comment by Legomegger** [comment]
Hello, as I understand there should be no difference of ours plugins, the action runs as a standalone program? Or should we include standard gem in our project? A bit confusing for me

**Comment by gnur** [comment]
I'm running into the same issue, is release v1.68.0 planned any time soon?
